### ISSUE TITLE
PromptTemplate 적용

### ISSUE THREAD

**Issue by effort-type** [DEU-NLP-Lab/DeuChatbot#1]
## 📝 Description
거대 언어 모델을 통해 받은 답변을 조금 더 자연스러운 표현으로 만들기 위해 프롬프트 템플릿을 적용하여 답변을 받을 수 있도록

기능을 추가할 예정이다.

## 📍 Todo
- [x] 프롬프트 템플릿 적용
- [x] 질의응답 시스템이 비슷한 문구가 여러 개 있을 때 혼잡해하는 것을 방지하기 위한 프롬프트 구성하기
- [x] 답변 질 향상 검토

## 📢 To Reviewers
@jaejin9771 @MynameisSejun
