### ISSUE TITLE
실험 자동화

### ISSUE THREAD

**Issue by effort-type** [DEU-NLP-Lab/DeuChatbot#17]
## 📝 Description
실험에 필요한 부분을 자동화하는 기능을 구현한다.

[Before]
질의를 입력하고 거대 언어 모델을 통해 답변을 받으면 임의로 판단하는 방식

[After]
1. 사용자가 직접 질문을 입력하는 것이 아닌 질문 리스트를 파일로 관리
2. 질의에 대해 응답을 받으면 질문과 응답 유사도를 코사인 유사도 함수를 통해 수치로 판단
3. 질의, 응답, 질문 응답 유사도에 대해 결과 파일을 만든다.

## 📍 Todo
- [x] 질의 리스트 파일을 읽어서 불러오는 함수 구현
- [x] 코사인 유사도 함수 구현
- [x] 질의, 응답, 질의 응답 유사도 결과 파일 생성, 저장하는 함수 구현
