### ISSUE TITLE
거대 언어 모델 후보군 추가

### ISSUE THREAD

**Issue by effort-type** [DEU-NLP-Lab/DeuChatbot#2]
## 📝 Description
성능 비교 실험에 사용할 거대언어모델 후보군을 여러 개 추가할 예정이다.
현재는 OpenAI 사의 GPT-3.5만 사용하고 있다.
유료, 무료 모두 사용해볼 예정이다.

## 📍 Todo
- [x] OpenAI GPT-3.5 거대언어모델 추가
- [x] OpenAI GPT-4 거대언어모델 추가
- [x] Google Gemini 1.5 Pro  거대언어모델 추가
- [ ] Upstage Solar 거대언어모델 추가
- [x] Anthropic Claude3 Opus 거대언어모델 추가
- [x] Anthropic Claude3 Sonnet 거대언어모델 추가
- [x] 야놀자 EEVE-Korean-10.8B 거대언어모델 추가 LMStudio 로컬 구동)
- [x] Meta Llama-3-8b 한국어 파인튜닝 모델 llama-3-8b-it-ko-chang LMStudio 로컬 구동)
- [x] Meta Llama-3-8B 한국어 파인튜닝 모델 Llama-3-Open-Ko-8B-Instruct-preview (LMStudio 로컬 구동)
- [x] Alibaba Qwen1.5-14B-Chat (LMStudio를 이용한 gguf 파일로 로컬에서 구동)
- [x] Maum-Ai Llama-3-MAAL-8B-Instruct-v0.1 (LMStudio 로컬 구동)
- [x] 거대언어모델 선택하는 chat_llm 함수 가독성을 높이기 위한 리팩토링

## 📢 To Reviewers
@jaejin9771 @MynameisSejun
