### ISSUE TITLE
프로젝트 문서화 진행하기

### ISSUE THREAD

**Issue by effort-type** [DEU-NLP-Lab/DeuChatbot#3]
## 📝 Description
본 프로젝트 문서화 진행하기

## 📍 Todo
- [x] 순서대로 따라서 이용할 수 있도록 문서 작성하기
- [x] 문서 가독성과 여러가지 요인들을 고려하여 검토하기
- [x] 패키지 버전 명시하기

## 📢 To Reviewers
@jaejin9771 @MynameisSejun
