### ISSUE TITLE
코드 모듈화 및 구조 변경

### ISSUE THREAD

**Issue by effort-type** [DEU-NLP-Lab/DeuChatbot#4]
## 📝 Description
기존 작성된 코드들끼리 불필요한 연관성을 제거하고 함수로 모듈화 진행 및 구조 변경

## 📍 Todo
- [x] 기존 코드 모듈화 진행
- [x] 질문을 위해서 계속해서 실행하는 것이 아니라 입력을 받아서 진행 가능하도록 변경
- [x] 임베딩 모델을 OpenAIEmbedding 모델과 HuggingFaceEmbedding 모델을 선택하여 사용할 수 있도록 변경함

## 📢 To Reviewers
@jaejin9771 @MynameisSejun
